# Generated by Django 5.2.6 on 2025-10-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompany',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(unique=True)),
                ('kl', models.IntegerField()),
                ('price', models.FloatField()),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('price3', models.FloatField()),
                ('name', models.CharField(unique=True)),
                ('gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.itemcompany')),
            ],
        ),
    ]
